nome=str(input("qual o sue nome? ")).strip()
print("carregando...")
print("seu nome em minusculo: {}".format(nome.lower()))
print("seu nome em maiusculo: {}".format(nome.upper()))
print("seu nome tem {} letras".format(len(nome)-nome.count(' ')))
print('seu primeiro nome tem {} letras'.format(nome.find(' ')))